<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{

    public function run(): void
    {
        $countries=array(
            array('AF', 'Afghanistan', 'أفغانستان', 'Afghan', 'أفغانستاني', 0),
            array('AL', 'Albania', 'ألبانيا', 'Albanian', 'ألباني', 0),
            array('AX', 'Aland Islands', 'جزر آلاند', 'Aland Islander', 'آلاندي', 0),
            array('DZ', 'Algeria', 'الجزائر', 'Algerian', 'جزائري', 0),
            array('AS', 'American Samoa', 'ساموا-الأمريكي', 'American Samoan', 'أمريكي سامواني', 0),
            array('AD', 'Andorra', 'أندورا', 'Andorran', 'أندوري', 0),
            array('AO', 'Angola', 'أنغولا', 'Angolan', 'أنقولي', 0),
            array('AI', 'Anguilla', 'أنغويلا', 'Anguillan', 'أنغويلي', 0),
            array('AQ', 'Antarctica', 'أنتاركتيكا', 'Antarctican', 'أنتاركتيكي', 0),
            array('AG', 'Antigua and Barbuda', 'أنتيغوا وبربودا', 'Antiguan', 'بربودي', 0),
            array('AR', 'Argentina', 'الأرجنتين', 'Argentinian', 'أرجنتيني', 0),
            array('AM', 'Armenia', 'أرمينيا', 'Armenian', 'أرميني', 0),
            array('AW', 'Aruba', 'أروبه', 'Aruban', 'أوروبهيني', 0),
            array('AU', 'Australia', 'أستراليا', 'Australian', 'أسترالي', 0),
            array('AT', 'Austria', 'النمسا', 'Austrian', 'نمساوي', 0),
            array('AZ', 'Azerbaijan', 'أذربيجان', 'Azerbaijani', 'أذربيجاني', 0),
            array('BS', 'Bahamas', 'الباهاماس', 'Bahamian', 'باهاميسي', 0),
            array('BH', 'Bahrain', 'البحرين', 'Bahraini', 'بحريني', 0),
            array('BD', 'Bangladesh', 'بنغلاديش', 'Bangladeshi', 'بنغلاديشي', 0),
            array('BB', 'Barbados', 'بربادوس', 'Barbadian', 'بربادوسي', 0),
            array('BY', 'Belarus', 'روسيا البيضاء', 'Belarusian', 'روسي', 0),
            array('BE', 'Belgium', 'بلجيكا', 'Belgian', 'بلجيكي', 0),
            array('BZ', 'Belize', 'بيليز', 'Belizean', 'بيليزي', 0),
            array('BJ', 'Benin', 'بنين', 'Beninese', 'بنيني', 0),
            array('BL', 'Saint Barthelemy', 'سان بارتيلمي', 'Saint Barthelmian', 'سان بارتيلمي', 0),
            array('BM', 'Bermuda', 'جزر برمودا', 'Bermudan', 'برمودي', 0),
            array('BT', 'Bhutan', 'بوتان', 'Bhutanese', 'بوتاني', 0),
            array('BO', 'Bolivia', 'بوليفيا', 'Bolivian', 'بوليفي', 0),
            array('BA', 'Bosnia and Herzegovina', 'البوسنة و الهرسك', 'Bosnian / Herzegovinian', 'بوسني/هرسكي', 0),
            array('BW', 'Botswana', 'بوتسوانا', 'Botswanan', 'بوتسواني', 0),
            array('BV', 'Bouvet Island', 'جزيرة بوفيه', 'Bouvetian', 'بوفيهي', 0),
            array('BR', 'Brazil', 'البرازيل', 'Brazilian', 'برازيلي', 0),
            array('IO', 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', 0),
            array('BN', 'Brunei Darussalam', 'بروني', 'Bruneian', 'بروني', 0),
            array('BG', 'Bulgaria', 'بلغاريا', 'Bulgarian', 'بلغاري', 0),
            array('BF', 'Burkina Faso', 'بوركينا فاسو', 'Burkinabe', 'بوركيني', 0),
            array('BI', 'Burundi', 'بوروندي', 'Burundian', 'بورونيدي', 0),
            array('KH', 'Cambodia', 'كمبوديا', 'Cambodian', 'كمبودي', 0),
            array('CM', 'Cameroon', 'كاميرون', 'Cameroonian', 'كاميروني', 0),
            array('CA', 'Canada', 'كندا', 'Canadian', 'كندي', 0),
            array('CV', 'Cape Verde', 'الرأس الأخضر', 'Cape Verdean', 'الرأس الأخضر', 0),
            array('KY', 'Cayman Islands', 'جزر كايمان', 'Caymanian', 'كايماني', 0),
            array('CF', 'Central African Republic', 'جمهورية أفريقيا الوسطى', 'Central African', 'أفريقي', 0),
            array('TD', 'Chad', 'تشاد', 'Chadian', 'تشادي', 0),
            array('CL', 'Chile', 'شيلي', 'Chilean', 'شيلي', 0),
            array('CN', 'China', 'الصين', 'Chinese', 'صيني', 0),
            array('CX', 'Christmas Island', 'جزيرة عيد الميلاد', 'Christmas Islander', 'جزيرة عيد الميلاد', 0),
            array('CC', 'Cocos (Keeling) Islands', 'جزر كوكوس', 'Cocos Islander', 'جزر كوكوس', 0),
            array('CO', 'Colombia', 'كولومبيا', 'Colombian', 'كولومبي', 0),
            array('KM', 'Comoros', 'جزر القمر', 'Comorian', 'جزر القمر', 0),
            array('CG', 'Congo', 'الكونغو', 'Congolese', 'كونغي', 0),
            array('CK', 'Cook Islands', 'جزر كوك', 'Cook Islander', 'جزر كوك', 0),
            array('CR', 'Costa Rica', 'كوستاريكا', 'Costa Rican', 'كوستاريكي', 0),
            array('HR', 'Croatia', 'كرواتيا', 'Croatian', 'كوراتي', 0),
            array('CU', 'Cuba', 'كوبا', 'Cuban', 'كوبي', 0),
            array('CY', 'Cyprus', 'قبرص', 'Cypriot', 'قبرصي', 0),
            array('CW', 'Curaçao', 'كوراساو', 'Curacian', 'كوراساوي', 0),
            array('CZ', 'Czech Republic', 'الجمهورية التشيكية', 'Czech', 'تشيكي', 0),
            array('DK', 'Denmark', 'الدانمارك', 'Danish', 'دنماركي', 0),
            array('DJ', 'Djibouti', 'جيبوتي', 'Djiboutian', 'جيبوتي', 0),
            array('DM', 'Dominica', 'دومينيكا', 'Dominican', 'دومينيكي', 0),
            array('DO', 'Dominican Republic', 'الجمهورية الدومينيكية', 'Dominican', 'دومينيكي', 0),
            array('EC', 'Ecuador', 'إكوادور', 'Ecuadorian', 'إكوادوري', 0),
            array('EG', 'Egypt', 'مصر', 'Egyptian', 'مصري', 1),
            array('SV', 'El Salvador', 'إلسلفادور', 'Salvadoran', 'سلفادوري', 0),
            array('GQ', 'Equatorial Guinea', 'غينيا الاستوائي', 'Equatorial Guinean', 'غيني', 0),
            array('ER', 'Eritrea', 'إريتريا', 'Eritrean', 'إريتيري', 0),
            array('EE', 'Estonia', 'استونيا', 'Estonian', 'استوني', 0),
            array('ET', 'Ethiopia', 'أثيوبيا', 'Ethiopian', 'أثيوبي', 0),
            array('FK', 'Falkland Islands (Malvinas)', 'جزر فوكلاند', 'Falkland Islander', 'فوكلاندي', 0),
            array('FO', 'Faroe Islands', 'جزر فارو', 'Faroese', 'جزر فارو', 0),
            array('FJ', 'Fiji', 'فيجي', 'Fijian', 'فيجي', 0),
            array('FI', 'Finland', 'فنلندا', 'Finnish', 'فنلندي', 0),
            array('FR', 'France', 'فرنسا', 'French', 'فرنسي', 0),
            array('GF', 'French Guiana', 'غويانا الفرنسية', 'French Guianese', 'غويانا الفرنسية', 0),
            array('PF', 'French Polynesia', 'بولينيزيا الفرنسية', 'French Polynesian', 'بولينيزيي', 0),
            array('TF', 'French Southern and Antarctic Lands', 'أراض فرنسية جنوبية وأنتارتيكية', 'French', 'أراض فرنسية جنوبية وأنتارتيكية', 0),
            array('GA', 'Gabon', 'الغابون', 'Gabonese', 'غابوني', 0),
            array('GM', 'Gambia', 'غامبيا', 'Gambian', 'غامبي', 0),
            array('GE', 'Georgia', 'جيورجيا', 'Georgian', 'جيورجي', 0),
            array('DE', 'Germany', 'ألمانيا', 'German', 'ألماني', 0),
            array('GH', 'Ghana', 'غانا', 'Ghanaian', 'غاني', 0),
            array('GI', 'Gibraltar', 'جبل طارق', 'Gibraltar', 'جبل طارق', 0),
            array('GG', 'Guernsey', 'غيرنزي', 'Guernsian', 'غيرنزي', 0),
            array('GR', 'Greece', 'اليونان', 'Greek', 'يوناني', 0),
            array('GL', 'Greenland', 'جرينلاند', 'Greenlandic', 'جرينلاندي', 0),
            array('GD', 'Grenada', 'غرينادا', 'Grenadian', 'غرينادي', 0),
            array('GP', 'Guadeloupe', 'جزر جوادلوب', 'Guadeloupe', 'جزر جوادلوب', 0),
            array('GU', 'Guam', 'جوام', 'Guamanian', 'جوامي', 0),
            array('GT', 'Guatemala', 'غواتيمال', 'Guatemalan', 'غواتيمالي', 0),
            array('GN', 'Guinea', 'غينيا', 'Guinean', 'غيني', 0),
            array('GW', 'Guinea-Bissau', 'غينيا-بيساو', 'Guinea-Bissauan', 'غيني', 0),
            array('GY', 'Guyana', 'غيانا', 'Guyanese', 'غياني', 0),
            array('HT', 'Haiti', 'هايتي', 'Haitian', 'هايتي', 0),
            array('HM', 'Heard and Mc Donald Islands', 'جزيرة هيرد وجزر ماكدونالد', 'Heard and Mc Donald Islanders', 'جزيرة هيرد وجزر ماكدونالد', 0),
            array('HN', 'Honduras', 'هندوراس', 'Honduran', 'هندوراسي', 0),
            array('HK', 'Hong Kong', 'هونغ كونغ', 'Hongkongese', 'هونغ كونغي', 0),
            array('HU', 'Hungary', 'المجر', 'Hungarian', 'مجري', 0),
            array('IS', 'Iceland', 'آيسلندا', 'Icelandic', 'آيسلندي', 0),
            array('IN', 'India', 'الهند', 'Indian', 'هندي', 0),
            array('IM', 'Isle of Man', 'جزيرة مان', 'Manx', 'ماني', 0),
            array('ID', 'Indonesia', 'أندونيسيا', 'Indonesian', 'أندونيسيي', 0),
            array('IR', 'Iran', 'إيران', 'Iranian', 'إيراني', 0),
            array('IQ', 'Iraq', 'العراق', 'Iraqi', 'عراقي', 0),
            array('IE', 'Ireland', 'إيرلندا', 'Irish', 'إيرلندي', 0),
            array('IL', 'Israel', 'إسرائيل', 'Israeli', 'إسرائيلي', 0),
            array('IT', 'Italy', 'إيطاليا', 'Italian', 'إيطالي', 0),
            array('CI', 'Ivory Coast', 'ساحل العاج', 'Ivory Coastian', 'ساحل العاج', 0),
            array('JE', 'Jersey', 'جيرزي', 'Jersian', 'جيرزي', 0),
            array('JM', 'Jamaica', 'جمايكا', 'Jamaican', 'جمايكي', 0),
            array('JP', 'Japan', 'اليابان', 'Japanese', 'ياباني', 0),
            array('JO', 'Jordan', 'الأردن', 'Jordanian', 'أردني', 0),
            array('KZ', 'Kazakhstan', 'كازاخستان', 'Kazakh', 'كازاخستاني', 0),
            array('KE', 'Kenya', 'كينيا', 'Kenyan', 'كيني', 0),
            array('KI', 'Kiribati', 'كيريباتي', 'I-Kiribati', 'كيريباتي', 0),
            array('KP', 'Korea(North Korea)', 'كوريا الشمالية', 'North Korean', 'كوري', 0),
            array('KR', 'Korea(South Korea)', 'كوريا الجنوبية', 'South Korean', 'كوري', 0),
            array('XK', 'Kosovo', 'كوسوفو', 'Kosovar', 'كوسيفي', 0),
            array('KW', 'Kuwait', 'الكويت', 'Kuwaiti', 'كويتي', 0),
            array('KG', 'Kyrgyzstan', 'قيرغيزستان', 'Kyrgyzstani', 'قيرغيزستاني', 0),
            array('LA', 'Lao PDR', 'لاوس', 'Laotian', 'لاوسي', 0),
            array('LV', 'Latvia', 'لاتفيا', 'Latvian', 'لاتيفي', 0),
            array('LB', 'Lebanon', 'لبنان', 'Lebanese', 'لبناني', 0),
            array('LS', 'Lesotho', 'ليسوتو', 'Basotho', 'ليوسيتي', 0),
            array('LR', 'Liberia', 'ليبيريا', 'Liberian', 'ليبيري', 0),
            array('LY', 'Libya', 'ليبيا', 'Libyan', 'ليبي', 0),
            array('LI', 'Liechtenstein', 'ليختنشتين', 'Liechtenstein', 'ليختنشتيني', 0),
            array('LT', 'Lithuania', 'لتوانيا', 'Lithuanian', 'لتوانيي', 0),
            array('LU', 'Luxembourg', 'لوكسمبورغ', 'Luxembourger', 'لوكسمبورغي', 0),
            array('LK', 'Sri Lanka', 'سريلانكا', 'Sri Lankian', 'سريلانكي', 0),
            array('MO', 'Macau', 'ماكاو', 'Macanese', 'ماكاوي', 0),
            array('MK', 'Macedonia', 'مقدونيا', 'Macedonian', 'مقدوني', 0),
            array('MG', 'Madagascar', 'مدغشقر', 'Malagasy', 'مدغشقري', 0),
            array('MW', 'Malawi', 'مالاوي', 'Malawian', 'مالاوي', 0),
            array('MY', 'Malaysia', 'ماليزيا', 'Malaysian', 'ماليزي', 0),
            array('MV', 'Maldives', 'المالديف', 'Maldivian', 'مالديفي', 0),
            array('ML', 'Mali', 'مالي', 'Malian', 'مالي', 0),
            array('MT', 'Malta', 'مالطا', 'Maltese', 'مالطي', 0),
            array('MH', 'Marshall Islands', 'جزر مارشال', 'Marshallese', 'مارشالي', 0),
            array('MQ', 'Martinique', 'مارتينيك', 'Martiniquais', 'مارتينيكي', 0),
            array('MR', 'Mauritania', 'موريتانيا', 'Mauritanian', 'موريتانيي', 0),
            array('MU', 'Mauritius', 'موريشيوس', 'Mauritian', 'موريشيوسي', 0),
            array('YT', 'Mayotte', 'مايوت', 'Mahoran', 'مايوتي', 0),
            array('MX', 'Mexico', 'المكسيك', 'Mexican', 'مكسيكي', 0),
            array('FM', 'Micronesia', 'مايكرونيزيا', 'Micronesian', 'مايكرونيزيي', 0),
            array('MD', 'Moldova', 'مولدافيا', 'Moldovan', 'مولديفي', 0),
            array('MC', 'Monaco', 'موناكو', 'Monacan', 'مونيكي', 0),
            array('MN', 'Mongolia', 'منغوليا', 'Mongolian', 'منغولي', 0),
            array('ME', 'Montenegro', 'الجبل الأسود', 'Montenegrin', 'الجبل الأسود', 0),
            array('MS', 'Montserrat', 'مونتسيرات', 'Montserratian', 'مونتسيراتي', 0),
            array('MA', 'Morocco', 'المغرب', 'Moroccan', 'مغربي', 0),
            array('MZ', 'Mozambique', 'موزمبيق', 'Mozambican', 'موزمبيقي', 0),
            array('MM', 'Myanmar', 'ميانمار', 'Myanmarian', 'ميانماري', 0),
            array('NA', 'Namibia', 'ناميبيا', 'Namibian', 'ناميبي', 0),
            array('NR', 'Nauru', 'نورو', 'Nauruan', 'نوري', 0),
            array('NP', 'Nepal', 'نيبال', 'Nepalese', 'نيبالي', 0),
            array('NL', 'Netherlands', 'هولندا', 'Dutch', 'هولندي', 0),
            array('AN', 'Netherlands Antilles', 'جزر الأنتيل الهولندي', 'Dutch Antilier', 'هولندي', 0),
            array('NC', 'New Caledonia', 'كاليدونيا الجديدة', 'New Caledonian', 'كاليدوني', 0),
            array('NZ', 'New Zealand', 'نيوزيلندا', 'New Zealander', 'نيوزيلندي', 0),
            array('NI', 'Nicaragua', 'نيكاراجوا', 'Nicaraguan', 'نيكاراجوي', 0),
            array('NE', 'Niger', 'النيجر', 'Nigerien', 'نيجيري', 0),
            array('NG', 'Nigeria', 'نيجيريا', 'Nigerian', 'نيجيري', 0),
            array('NU', 'Niue', 'ني', 'Niuean', 'ني', 0),
            array('NF', 'Norfolk Island', 'جزيرة نورفولك', 'Norfolk Islander', 'نورفوليكي', 0),
            array('MP', 'Northern Mariana Islands', 'جزر ماريانا الشمالية', 'Northern Marianan', 'ماريني', 0),
            array('NO', 'Norway', 'النرويج', 'Norwegian', 'نرويجي', 0),
            array('OM', 'Oman', 'عمان', 'Omani', 'عماني', 0),
            array('PK', 'Pakistan', 'باكستان', 'Pakistani', 'باكستاني', 0),
            array('PW', 'Palau', 'بالاو', 'Palauan', 'بالاوي', 0),
            array('PS', 'Palestine', 'فلسطين', 'Palestinian', 'فلسطيني', 0),
            array('PA', 'Panama', 'بنما', 'Panamanian', 'بنمي', 0),
            array('PG', 'Papua New Guinea', 'بابوا غينيا الجديدة', 'Papua New Guinean', 'بابوي', 0),
            array('PY', 'Paraguay', 'باراغواي', 'Paraguayan', 'بارغاوي', 0),
            array('PE', 'Peru', 'بيرو', 'Peruvian', 'بيري', 0),
            array('PH', 'Philippines', 'الفليبين', 'Filipino', 'فلبيني', 0),
            array('PN', 'Pitcairn', 'بيتكيرن', 'Pitcairn Islander', 'بيتكيرني', 0),
            array('PL', 'Poland', 'بولندا', 'Polish', 'بولندي', 0),
            array('PT', 'Portugal', 'البرتغال', 'Portuguese', 'برتغالي', 0),
            array('PR', 'Puerto Rico', 'بورتو ريكو', 'Puerto Rican', 'بورتي', 0),
            array('QA', 'Qatar', 'قطر', 'Qatari', 'قطري', 0),
            array('RE', 'Reunion Island', 'ريونيون', 'Reunionese', 'ريونيوني', 0),
            array('RO', 'Romania', 'رومانيا', 'Romanian', 'روماني', 0),
            array('RU', 'Russian', 'روسيا', 'Russian', 'روسي', 0),
            array('RW', 'Rwanda', 'رواندا', 'Rwandan', 'رواندا', 0),
            array('KN', 'Saint Kitts and Nevis', 'سانت كيتس ونيفس,', 'Kittitian/Nevisian', 'سانت كيتس ونيفس', 0),
            array('MF', 'Saint Martin (French part)', 'ساينت مارتن فرنسي', 'St. Martian(French)', 'ساينت مارتني فرنسي', 0),
            array('SX', 'Sint Maarten (Dutch part)', 'ساينت مارتن هولندي', 'St. Martian(Dutch)', 'ساينت مارتني هولندي', 0),
            array('LC', 'Saint Pierre and Miquelon', 'سان بيير وميكلون', 'St. Pierre and Miquelon', 'سان بيير وميكلوني', 0),
            array('VC', 'Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين', 'Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين', 0),
            array('WS', 'Samoa', 'ساموا', 'Samoan', 'ساموي', 0),
            array('SM', 'San Marino', 'سان مارينو', 'Sammarinese', 'ماريني', 0),
            array('ST', 'Sao Tome and Principe', 'ساو تومي وبرينسيبي', 'Sao Tomean', 'ساو تومي وبرينسيبي', 0),
            array('SA', 'Saudi Arabia', 'المملكة العربية السعودية', 'Saudi Arabian', 'سعودي', 0),
            array('SN', 'Senegal', 'السنغال', 'Senegalese', 'سنغالي', 0),
            array('RS', 'Serbia', 'صربيا', 'Serbian', 'صربي', 0),
            array('SC', 'Seychelles', 'سيشيل', 'Seychellois', 'سيشيلي', 0),
            array('SL', 'Sierra Leone', 'سيراليون', 'Sierra Leonean', 'سيراليوني', 0),
            array('SG', 'Singapore', 'سنغافورة', 'Singaporean', 'سنغافوري', 0),
            array('SK', 'Slovakia', 'سلوفاكيا', 'Slovak', 'سولفاكي', 0),
            array('SI', 'Slovenia', 'سلوفينيا', 'Slovenian', 'سولفيني', 0),
            array('SB', 'Solomon Islands', 'جزر سليمان', 'Solomon Island', 'جزر سليمان', 0),
            array('SO', 'Somalia', 'الصومال', 'Somali', 'صومالي', 0),
            array('ZA', 'South Africa', 'جنوب أفريقيا', 'South African', 'أفريقي', 0),
            array('GS', 'South Georgia and the South Sandwich', 'المنطقة القطبية الجنوبية', 'South Georgia and the South Sandwich', 'لمنطقة القطبية الجنوبية', 0),
            array('SS', 'South Sudan', 'السودان الجنوبي', 'South Sudanese', 'سوادني جنوبي', 0),
            array('ES', 'Spain', 'إسبانيا', 'Spanish', 'إسباني', 0),
            array('SH', 'Saint Helena', 'سانت هيلانة', 'St. Helenian', 'هيلاني', 0),
            array('SD', 'Sudan', 'السودان', 'Sudanese', 'سوداني', 0),
            array('SR', 'Suriname', 'سورينام', 'Surinamese', 'سورينامي', 0),
            array('SJ', 'Svalbard and Jan Mayen', 'سفالبارد ويان ماين', 'Svalbardian/Jan Mayenian', 'سفالبارد ويان ماين', 0),
            array('SZ', 'Swaziland', 'سوازيلند', 'Swazi', 'سوازيلندي', 0),
            array('SE', 'Sweden', 'السويد', 'Swedish', 'سويدي', 0),
            array('CH', 'Switzerland', 'سويسرا', 'Swiss', 'سويسري', 0),
            array('SY', 'Syria', 'سوريا', 'Syrian', 'سوري', 0),
            array('TW', 'Taiwan', 'تايوان', 'Taiwanese', 'تايواني', 0),
            array('TJ', 'Tajikistan', 'طاجيكستان', 'Tajikistani', 'طاجيكستاني', 0),
            array('TZ', 'Tanzania', 'تنزانيا', 'Tanzanian', 'تنزانيي', 0),
            array('TH', 'Thailand', 'تايلندا', 'Thai', 'تايلندي', 0),
            array('TL', 'Timor-Leste', 'تيمور الشرقية', 'Timor-Lestian', 'تيموري', 0),
            array('TG', 'Togo', 'توغو', 'Togolese', 'توغي', 0),
            array('TK', 'Tokelau', 'توكيلاو', 'Tokelaian', 'توكيلاوي', 0),
            array('TO', 'Tonga', 'تونغا', 'Tongan', 'تونغي', 0),
            array('TT', 'Trinidad and Tobago', 'ترينيداد وتوباغو', 'Trinidadian/Tobagonian', 'ترينيداد وتوباغو', 0),
            array('TN', 'Tunisia', 'تونس', 'Tunisian', 'تونسي', 0),
            array('TR', 'Turkey', 'تركيا', 'Turkish', 'تركي', 0),
            array('TM', 'Turkmenistan', 'تركمانستان', 'Turkmen', 'تركمانستاني', 0),
            array('TC', 'Turks and Caicos Islands', 'جزر توركس وكايكوس', 'Turks and Caicos Islands', 'جزر توركس وكايكوس', 0),
            array('TV', 'Tuvalu', 'توفالو', 'Tuvaluan', 'توفالي', 0),
            array('UG', 'Uganda', 'أوغندا', 'Ugandan', 'أوغندي', 0),
            array('UA', 'Ukraine', 'أوكرانيا', 'Ukrainian', 'أوكراني', 0),
            array('AE', 'United Arab Emirates', 'الإمارات العربية المتحدة', 'Emirati', 'إماراتي', 0),
            array('GB', 'United Kingdom', 'المملكة المتحدة', 'British', 'بريطاني', 0),
            array('US', 'United States', 'الولايات المتحدة', 'American', 'أمريكي', 0),
            array('UM', 'US Minor Outlying Islands', 'قائمة الولايات والمناطق الأمريكية', 'US Minor Outlying Islander', 'أمريكي', 0),
            array('UY', 'Uruguay', 'أورغواي', 'Uruguayan', 'أورغواي', 0),
            array('UZ', 'Uzbekistan', 'أوزباكستان', 'Uzbek', 'أوزباكستاني', 0),
            array('VU', 'Vanuatu', 'فانواتو', 'Vanuatuan', 'فانواتي', 0),
            array('VE', 'Venezuela', 'فنزويلا', 'Venezuelan', 'فنزويلي', 0),
            array('VN', 'Vietnam', 'فيتنام', 'Vietnamese', 'فيتنامي', 0),
            array('VI', 'Virgin Islands (U.S.)', 'الجزر العذراء الأمريكي', 'American Virgin Islander', 'أمريكي', 0),
            array('VA', 'Vatican City', 'فنزويلا', 'Vatican', 'فاتيكاني', 0),
            array('WF', 'Wallis and Futuna Islands', 'والس وفوتونا', 'Wallisian/Futunan', 'فوتوني', 0),
            array('EH', 'Western Sahara', 'الصحراء الغربية', 'Sahrawian', 'صحراوي', 0),
            array('YE', 'Yemen', 'اليمن', 'Yemeni', 'يمني', 0),
            array('ZM', 'Zambia', 'زامبيا', 'Zambian', 'زامبياني', 0),
            array('ZW', 'Zimbabwe', 'زمبابوي', 'Zimbabwean', 'زمبابوي', 0)
        );

       foreach($countries as $country){
            DB::table("countries")->insert([
                "country_code" => $country[0],
                "country_enName" => $country[1],
                "country_arName" => $country[2],
                "country_enNationality" => $country[3],
                "country_arNationality" => $country[4],
                "active" => $country[5]
            ]);
       }
    }
}
